tasks:
  - name: setup
    before: |
      pip install -r requirements.txt
      jupyter notebook --generate-config
      echo -e '\nc.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py
      echo -e '\nc.ContentsManager.default_jupytext_formats = "ipynb,py"' >> ~/.jupyter/jupyter_notebook_config.py
      echo -e '\nc.NotebookApp.password = ""' >> ~/.jupyter/jupyter_notebook_config.py
    init: |
      jupyter notebook --ip=*
  - name: new shell
    init: |
      pip install kaggle
      read -p "Enter Your Kaggle Account Name: " KAGGLE_ID
      read -p "Enter Your Kaggle API key: " KAGGLE_KEY
      export KAGGLE_USERNAME=$KAGGLE_ID
      export KAGGLE_KEY=$KAGGLE_KEY
      kaggle d download -d salehahmedrony/gender-statistics -f Gender_StatsData.csv
      echo 'python intro_dash.py'
      echo 'streamlit run intro_streamlit.py'
    openMode: split-right